"""Add phone and address fields to User

Revision ID: 565dce3d1f2a
Revises: 7bb56c78fcd1
Create Date: 2026-01-28 12:34:38.589699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565dce3d1f2a'
down_revision = '7bb56c78fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
