"""Add education, professional, other docs, avatar fields to User

Revision ID: 5a679fc8864d
Revises: 3b5ab324d659
Create Date: 2026-01-28 20:50:47.887151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a679fc8864d'
down_revision = '3b5ab324d659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('professional', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_docs_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('other_docs_path')
        batch_op.drop_column('professional')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
