"""Add summary field to Job

Revision ID: 704982fcb155
Revises: 7a43fbd60ca0
Create Date: 2026-02-02 21:04:29.738339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704982fcb155'
down_revision = '7a43fbd60ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users\\seeker')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('summary')

    op.create_table('users\\seeker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('skills', sa.VARCHAR(length=200), nullable=True),
    sa.Column('resume_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('company', sa.VARCHAR(length=200), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=200), nullable=True),
    sa.Column('logo_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('education', sa.VARCHAR(length=200), nullable=True),
    sa.Column('professional', sa.TEXT(), nullable=True),
    sa.Column('other_docs_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
