"""Add job fields

Revision ID: 7bb56c78fcd1
Revises: d8c24f1824f4
Create Date: 2026-01-20 18:11:13.533497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb56c78fcd1'
down_revision = 'd8c24f1824f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('job_type')
        batch_op.drop_column('location')
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('qualifications')

    # ### end Alembic commands ###
