"""Add new profile fields to User

Revision ID: 8039185b25c6
Revises: 80581c9d92a6
Create Date: 2026-02-03 00:36:27.931029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8039185b25c6'
down_revision = '80581c9d92a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reporting_to', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('joined_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notice_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('professional',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('professional',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('notice_period')
        batch_op.drop_column('status')
        batch_op.drop_column('joined_on')
        batch_op.drop_column('reporting_to')
        batch_op.drop_column('designation')
        batch_op.drop_column('department')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('company_contact')
        batch_op.drop_column('company_name')
        batch_op.drop_column('nationality')
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
