"""Add is_featured column to Job

Revision ID: 80581c9d92a6
Revises: 4f691d43d0fc
Create Date: 2026-02-02 21:16:50.335622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80581c9d92a6'
down_revision = '4f691d43d0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
